CREATE TABLE "presentation_registration" (
     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     "participant_congress_id" bigint NOT NULL,
     "presentation_id" bigint NOT NULL,
     "time_block_id" bigint NOT NULL,
     "registered_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);