CREATE TABLE "speaker" (
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "names" varchar(40) NOT NULL,
   "last_name" varchar(40) NOT NULL,
   "academic_degree_id" bigint NOT NULL,
   "congress_id" bigint NOT NULL,
   "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);