CREATE TABLE "comment" (
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "participant_id" bigint NOT NULL,
   "content" text NOT NULL,
   "commented_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
   "is_active" bool NOT NULL DEFAULT true
);