CREATE TABLE "vote" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "score" SMALLINT NOT NULL CHECK (score >= 1 AND score <= 5) DEFAULT 1,
    "participant_congress_id" bigint NOT NULL,
    "presentation_id" bigint NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);