CREATE TABLE "time_block" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conference_day_id" bigint NOT NULL,
  "start_time" time NOT NULL,
  "end_time" time NOT NULL,
  "location_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  CHECK (start_time < end_time)
);