CREATE TABLE "attendance" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "participant_congress_id" bigint NOT NULL,
  "time_block_id" bigint NOT NULL,
  "attended_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);