CREATE TABLE "participant" (
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "names" varchar(40) NOT NULL,
   "paternal_surname" varchar(25) NOT NULL,
   "maternal_surname" varchar(25) NOT NULL,
   "document_number" varchar(20) UNIQUE NOT NULL,
   "email" varchar(255) UNIQUE NOT NULL,
   "participant_type_id" bigint NOT NULL,
   "professional_school_id" bigint NOT NULL,
   "qr_code" varchar(255),
   "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);