CREATE TABLE "participant_congress" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "participant_id" bigint NOT NULL,
    "congress_id" bigint NOT NULL,
    "status" varchar(15) NOT NULL CHECK (status IN ('MATRICULADO', 'EN OBSERVACION')) DEFAULT 'MATRICULADO',
    "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);