CREATE TABLE "congress" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" varchar(8) UNIQUE NOT NULL,
    "name" varchar(255) NOT NULL,
    "start_date" date NOT NULL,
    "end_date" date NOT NULL,
    "min_attendance_required" int NOT NULL DEFAULT 0,
    "max_refreshments_allowed" int NOT NULL DEFAULT 0,
    "daily_refreshment_limit" int NOT NULL DEFAULT 0,
    "is_active" bool NOT NULL DEFAULT true,
    "professional_school_id" bigint NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CHECK (start_date <= end_date)
);