CREATE TABLE "professional_school" (
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "code" varchar(8) UNIQUE NOT NULL,
   "name" varchar(255) NOT NULL,
   "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);