CREATE TABLE "user" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "names" varchar(40) NOT NULL,
    "paternal_surname" varchar(25) NOT NULL,
    "maternal_surname" varchar(25) NOT NULL,
    "email" varchar(255) UNIQUE NOT NULL,
    "password" varchar(255) NOT NULL,
    "is_active" bool NOT NULL DEFAULT true,
    "professional_school_id" bigint NOT NULL,
    "participant_type_id" bigint NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);