CREATE TABLE "presentation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "is_active" bool NOT NULL DEFAULT true,
    "speaker_id" bigint NOT NULL,
    "congress_id" bigint NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);